### ISSUE TITLE
Works with Webpack?

### ISSUE THREAD

**Issue by rossknudsen** [hediet/node-reload#8]
I use webpack to minify my vscode extension.  Will your library hot reload in that case?

**Comment by hediet** [comment]
Sadly not - there is just no way. This is why I use webpack only for release, and ts watch for dev in my vscode extensions.

**Comment by hediet** [comment]
Maybe somehow HMR can be turned on in webpack though?

**Comment by rossknudsen** [comment]
Ok, thanks for the heads up.  I might have to implement your suggestion and develop with the TS instead.  Cheers.

**Comment by hediet** [comment]
I do this here: https://github.com/hediet/vscode-debug-visualizer/blob/master/extension/package.json#L98
